# Generated by ext/qpid-proton/build.sh.
module Qpid
  module Proton
    @[Link(ldflags: "#{__DIR__}/../../../ext/qpid-proton/install/lib/libqpid-proton-core-static.a")]
    lib Lib
    end
  end
end
