#!/bin/sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
root_dir=$(CDPATH= cd -- "$script_dir/../.." && pwd)
source_dir="$root_dir/vendor/qpid-proton"
build_dir="$root_dir/ext/qpid-proton/build"
install_dir="$root_dir/ext/qpid-proton/install"
link_file="$root_dir/src/qpid/proton/lib_vendored_link.cr"

if [ ! -f "$source_dir/CMakeLists.txt" ]; then
  echo "vendor/qpid-proton is missing. Run: git submodule update --init vendor/qpid-proton" >&2
  exit 1
fi

jobs=${QPID_PROTON_BUILD_JOBS:-}
if [ -z "$jobs" ]; then
  jobs=$(getconf _NPROCESSORS_ONLN 2>/dev/null || printf '1')
fi

cmake -S "$source_dir" -B "$build_dir" \
  -DCMAKE_BUILD_TYPE=MinSizeRel \
  -DCMAKE_INSTALL_PREFIX="$install_dir" \
  -DINCLUDE_INSTALL_DIR=include \
  -DLIB_INSTALL_DIR=lib \
  -DBUILD_STATIC_LIBS=ON \
  -DBUILD_TESTING=OFF \
  -DBUILD_EXAMPLES=OFF \
  -DBUILD_TOOLS=OFF \
  -DBUILD_TLS=OFF \
  -DBUILD_BINDINGS= \
  -DPROACTOR=none \
  -DSSL_IMPL=none \
  -DSASL_IMPL=none

cmake --build "$build_dir" --target qpid-proton-core-static --parallel "$jobs"

mkdir -p "$install_dir/lib" "$install_dir/include"

archive=$(find "$build_dir" -name 'libqpid-proton-core-static.a' -type f | head -n 1)
if [ -z "$archive" ]; then
  echo "Could not find built libqpid-proton-core-static.a under $build_dir" >&2
  exit 1
fi

cp "$archive" "$install_dir/lib/libqpid-proton-core-static.a"
if [ -d "$build_dir/c/include/proton" ]; then
  rm -rf "$install_dir/include/proton"
  cp -R "$build_dir/c/include/proton" "$install_dir/include/proton"
fi

cat > "$link_file" <<'CRYSTAL'
# Generated by ext/qpid-proton/build.sh.
module Qpid
  module Proton
    @[Link(ldflags: "#{__DIR__}/../../../ext/qpid-proton/install/lib/libqpid-proton-core-static.a")]
    lib Lib
    end
  end
end
CRYSTAL

echo "Built vendored Proton core: $install_dir/lib/libqpid-proton-core-static.a"
